
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install -y git
CMD git --version
#CMD imprime el parámetro que le indiquemos. Se puede sobreescribir por línea de comando.
#ENTRYPOINT imprime el parámetro pero no se puede sobreescribir por comando, siempre mostrará el parámetro


